name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v6

      - name: إعداد Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: إعداد Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.11.1'

      - name: بناء APK
        run: gradle assembleDebug

      - name: البحث عن APK
        run: |
          echo "APK files:"
          find . -type f -name "*.apk" -print

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: AzzatBluetoothChat-debug
          path: '**/build/outputs/apk/debug/*.apk'
          if-no-files-found: error
